# -*- coding: utf-8 -*-
{
    'name': 'Facturas',
    'version': 'saas~16.1.1.0',
    'category': 'Studio',
    'description': u"""


This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.


""",
    'author': 'modulosxe',
    'depends': [
        'base',
        'web_studio',
    ],
    'data': [
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_menu.xml',
        'data/ir_model_access.xml',
        'data/ir_default.xml',
    ],
    'application': False,
    'license': 'OPL-1',
}
